[build]
  command = """
    pip install --upgrade pip
    pip install -r requirements.txt
    mkdir -p netlify/functions
    cp streamlit_app.py netlify/functions/
  """
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/streamlit_app"
  status = 200
